apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Base64 encoded values
  # username: bloguser (YmxvZ3VzZXI=)
  # password: blogpassword (YmxvZ3Bhc3N3b3Jk)
  # database: blogdb (YmxvZ2Ri)
  username: YmxvZ3VzZXI=
  password: YmxvZ3Bhc3N3b3Jk
  database: YmxvZ2Ri
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded values
  # jwt-secret: your-super-secret-jwt-key-change-this-in-production
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u
